# -*- coding: utf-8 -*-
"""Linear_Regression1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10yhiJs2bpSN_qDr_y3nx4O3PxKUUKNfW
"""

import numpy as np
import matplotlib.pyplot as plt

def generate_data(n_samples=50, noise=5.0):
    np.random.seed(42)
    X = np.linspace(-10, 10, n_samples)
    # Ground truth line: y = 4x + 5
    A = 4
    B = 5
    noise = np.random.randn(n_samples) * noise
    y = A * X + B + noise
    return X, y

# plot
X, y = generate_data(n_samples=50, noise=5.0)
plt.scatter(X, y, color='green', label='Data Points')
plt.title("Generated Data")
plt.xlabel("$x$")
plt.ylabel("$y$")
plt.legend()
plt.show()